function O=thirdorder(B,A,A2,BA,BA2,BAB,BAA,Ibdt,IadW,Ia2dt,IbIadWdt,IaIbdtdW,...
                      Ia2Ibdtdt,IbIa2dtdt,IIadWIbdtadW,IbIadW2ds,IaIaIbdtdWdW,...
                      IaIbIadWdtdt,IbIbdtIadWdt,IbIbIadWdtdt,IbIaIbdtdtdt,...
                      IaIbdt2dW)
%     O=B.*Ibdt+A.*IadW+...
%       (-A2.*Ia2dt+BA.*(IbIadWdt-IaIbdtdW)).*(.5)+...
%       BA2.*(Ia2Ibdtdt-IbIa2dtdt).*(.25)+...
%       BAA.*(Ia2Ibdtdt.*(1/12)-...
%             IIadWIbdtadW.*(1/12)+...
%             IbIadW2dW.*(1/12)+...
%             IaIaIbdtdWdW.*(.25)-...
%             IaIbIadWdtdt.*(.25))+...
%       BAB.*(IbIbdtIadWdt.*(1/12)-...
%             IbIbIadWdtdt.*(.25)+...
%             IbIaIbdtdtdt.*(.25)-...
%             IaIbdt2dW.*(1/12));
    O=B.*Ibdt+A.*IadW+...
      (-A2.*Ia2dt+BA.*(IbIadWdt-IaIbdtdW)).*(.5)+...
      BA2.*(Ia2Ibdtdt-IbIa2dtdt).*(.25)+...
      BAA.*(Ia2Ibdtdt.*(1/12)-...
            IIadWIbdtadW.*(1/12)+...
            IbIadW2ds.*(1/12)+...
            IaIaIbdtdWdW.*(.25)-...
            IaIbIadWdtdt.*(.25))+...
      BAB.*(IbIbdtIadWdt.*(1/12)-...
            IbIbIadWdtdt.*(.25)+...
            IbIaIbdtdtdt.*(.25)-...
            IaIbdt2dW.*(1/12));
end
