function O=thirdorder(B,A,A2,BA,BAA,BAB,t,W,IW,IsW,IW2)
    O=B.*t+A.*W+...
          -.5.*A2.*t+BA.*IW-.5.*BA.*t.*W+...
          -(1/12).*BAB.*t.^2.*W+...
          (1/12).*BAA.*t.*W.^2+...
          BAB.*IsW-...
          .5.*BAA.*W.*IW-...
          .5.*BAB.*t.*IW+...
          .5.*BAA.*IW2;
end