function O=secondorder(B1,B2,A,A2,B1A,B2A,B1B2,t,Ibdt,IadW,Ia2dt,IbIadWdt,IIadWdt,IaIbdtdW,IsadW,IIbdtdt,Isbdt)
    O=B1.*t+B2.*Ibdt+A.*IadW+...
      (-A2.*Ia2dt+...
       B1A.*(IIadWdt-IsadW)+...
       B2A.*(IbIadWdt-IaIbdtdW)+...
       B1B2.*(IIbdtdt-Isbdt)).*(.5);
end